### PR TITLE
added function for specifying webhookUrl with webhookId and JSON resp…

### PR DESCRIPTION
**Pull request by kunruh-refer**
…onse

### CODE REVIEW

**Comment by kunruh-refer** [comment]
Whoops, wanted to test first.

**Comment by sb8244** [comment]
Awesome, I'll put it in with a test.

Do you use this module at your company?

**Comment by sb8244** [comment]
I would suggest https://www.npmjs.com/package/fullcontact as I haven't updated this in 2 years. I have moved into a Ruby position since then, and so I do not maintain this library any more.

**Comment by kunruh-refer** [comment]
We might, but I don't know for sure yet. Mean't to merge with my own first
before submitting the pull request.

**Comment by kunruh-refer** [comment]
Yep, saw that one too. I'll be trying that one as well, but it needs to send the response to the webhook as a json with a custom ID as well. From what I could see, they don't specify that webhookBody=json, so unless I missed it, it wouldn't work either.

**Pull request closed without merging**
